// Copyright (c) 2025 Razisafir. All rights reserved.
// Kovix proprietary code. See CONSTRUCT_LICENSE.txt.
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * A refinement question generated by the AI to clarify the user's idea.
 */
export interface IRefinementQuestion {
	/** Unique identifier for this question. */
	readonly id: string;
	/** The question text. */
	readonly text: string;
	/** Category of the question (scope, tech, ux, etc.). */
	readonly category: 'scope' | 'technical' | 'ux' | 'architecture' | 'constraints' | 'goals';
	/** Suggested answers or options. */
	readonly suggestions?: string[];
	/** Whether this question is required. */
	readonly required?: boolean;
}

/**
 * A user's answer to a refinement question.
 */
export interface IRefinementAnswer {
	/** The question ID this answer corresponds to. */
	readonly questionId: string;
	/** The user's answer text. */
	readonly text: string;
	/** Whether the user skipped this question. */
	readonly skipped: boolean;
}

/**
 * A refined and clarified version of the user's original idea.
 * Produced after the refinement Q&A process completes.
 */
export interface IRefinedIdea {
	/** The original user input. */
	readonly originalIdea: string;
	/** The refined, detailed idea description. */
	readonly refinedDescription: string;
	/** Key requirements extracted from the Q&A. */
	readonly requirements: string[];
	/** Suggested technical approach. */
	readonly technicalApproach: string;
	/** Identified risks or constraints. */
	readonly risks: string[];
	/** Clarified scope boundaries. */
	readonly scope: {
		readonly inScope: string[];
		readonly outOfScope: string[];
	};
	/** Confidence score 0-1 of how well the idea is understood. */
	readonly confidence: number;
}

/**
 * Events emitted during the refinement process.
 */
export type RefinementEvent =
	| { type: 'questions_generated'; questions: IRefinementQuestion[] }
	| { type: 'answer_received'; answer: IRefinementAnswer }
	| { type: 'more_questions'; questions: IRefinementQuestion[] }
	| { type: 'refinement_complete'; refinedIdea: IRefinedIdea }
	| { type: 'error'; text: string };
